<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Resource Include="Shaders\*.ps" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Shaders\*.hlsl" />
    </ItemGroup>

    <ItemGroup>
      <ClCompile Include="Shaders\Difference.hlsl" />
      <ClCompile Include="Shaders\Exclusion.hlsl" />
    </ItemGroup>
</Project>
